// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_psico_killer = "CgkIv_alrLwaEAIQAw"; // <GPGSID>
        public const string achievement_hello_world = "CgkIv_alrLwaEAIQAQ"; // <GPGSID>
        public const string achievement_gun_lover = "CgkIv_alrLwaEAIQBw"; // <GPGSID>
        public const string achievement_seek_and_destroy = "CgkIv_alrLwaEAIQBA"; // <GPGSID>
        public const string achievement_headhunter = "CgkIv_alrLwaEAIQBQ"; // <GPGSID>
        public const string achievement_war_machine = "CgkIv_alrLwaEAIQCA"; // <GPGSID>
        public const string achievement_net_guardian = "CgkIv_alrLwaEAIQAg"; // <GPGSID>
        public const string achievement_secondary_weapon = "CgkIv_alrLwaEAIQBg"; // <GPGSID>

}

